server:
  port: 18020

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:18761/eureka}
  instance:
    preferIpAddress: true

spring:
  jmx: 
    enabled: true
  boot:
    admin:
      client:
        url: http://localhost:19090
        username: admin
        password: admin

management:
  endpoints:
    web:
      exposure:
        include: "*"