server:
  port: 28020

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:28761/eureka}
  instance:
    preferIpAddress: true

spring:
  jmx: 
    enabled: true
  boot:
    admin:
      client:
        url: http://localhost:29090
        username: admin
        password: admin

management:
  endpoints:
    web:
      exposure:
        include: "*"