spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: agro-products-ms
          uri: lb://agro-products-ms
          predicates:
            - Path=/api/v1/products/**
        - id: agro-people-ms
          uri: lb://agro-people-ms
          predicates:
            - Path=/api/v1/people/**

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

management:
  endpoints:
    web:
      exposure:
        include: "*"