server:
  port: 18010
  
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:18761/eureka
  server:
    waitTimeInMsWhenSyncEmpty: 0

spring:
  jmx: 
    enabled: true
  boot:
    admin:
      client:
        url: http://localhost:19090
        username: admin
        password: admin

management:
  endpoints:
    web:
      exposure:
        include: "*"